### ISSUE TITLE
Jpeg.open_buffer fails with error “Symbol not found: _fmemopen” on OS X

### ISSUE THREAD

**Issue by Envek** [masarakki/jpeg#22]
I'm trying to instantiate `Jpeg::Image` from file contents in memory on OS X 10.12 and Ruby 2.4.0.

Interpreter crashes with error:

```
[1] pry(main)> Jpeg.open_buffer(File.read("/Users/anovikov/Downloads/some.jpg", mode: 'rb'))
dyld: lazy symbol binding failed: Symbol not found: _fmemopen
  Referenced from: /Users/anovikov/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/bundler/gems/jpeg-9189f48bd042/lib/jpeg/jpeg.bundle
  Expected in: flat namespace
```

I've installed libjpeg from Homebrew with `brew install libjpeg`. Gem installed successfully.

Any ideas why it can occur?

Loading via file path works perfectly.

**Comment by Envek** [comment]
And there is `fmemopen` in `jpeg.bundle`:

```
$ nm -g /Users/anovikov/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/bundler/gems/jpeg-9189f48bd042/lib/jpeg/jpeg.bundle
00000000000013f0 T _Init_jpeg
0000000000001420 T _Init_jpeg_error
0000000000001450 T _Init_jpeg_image
                 U _fclose
                 U _fmemopen
…output truncated…
```

**Comment by masarakki** [comment]
please run `man fmemopen`

In my case, 

```
FMEMOPEN(3)                Linux Programmer's Manual               FMEMOPEN(3)

NAME
       fmemopen -  open memory as stream

SYNOPSIS
       #include <stdio.h>

       FILE *fmemopen(void *buf, size_t size, const char *mode);

   Feature Test Macro Requirements for glibc (see feature_test_macros(7)):

       fmemopen():
           Since glibc 2.10:
               _POSIX_C_SOURCE >= 200809L
           Before glibc 2.10:
               _GNU_SOURCE
```

**Comment by Envek** [comment]
No manual entry for fmemopen

**Comment by Envek** [comment]
Yes, some people writes that it doesn't exist in BSD systems:

> This method does not exist on BSD operating systems (specifically Mac OS X and iOS). It is possible to recreate this functionality using a BSD-specific method called `funopen`.

See http://stackoverflow.com/questions/38219285/fmemopen-error-on-mac-os-x and https://github.com/NimbusKit/memorymapping

**Comment by masarakki** [comment]
thanks!!

**Comment by masarakki** [comment]
please try pr #23 

```
git checkout

bundle install
rake compile
```

fix checking of libjpeg version.
libjpeg 8.x is 7 years old, so every systems may have newer version of it.

**Comment by Envek** [comment]
Thank you! #23 works!

**Comment by masarakki** [comment]
0.7.1 was released. thanks!!!
